name: Smart API from diff repo

on: 
    workflow_dispatch:

jobs:
 Test:
    runs-on: ubuntu-latest
    steps:
        
        - name: checkout repo content
          uses: actions/checkout@v3
          with:
            repository: tushar-lakhe/Smart-API-Automation
            token: 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 
            ref: main
          
        - name: setup python
          uses: actions/setup-python@v4
          with: 
            python-version: '3.9'
          
         
        - name: List Dir
          run: |
                pwd
                ls
                cd /home/runner/work/Karate-Demo/Karate-Demo
                ls
                cd IdeaProjects/SmartAPIautomationframework/src/test/java/examples/users/pythonController
                ls
                pwd
               
